export const CREATE_PERMISSION_SUCCESS = "CREATE_PERMISSION_SUCCESS"
export const CREATE_PERMISSION_FAILURE = "CREATE_PERMISSION_FAILURE"
export const CREATE_PERMISSION_LOADING = "CREATE_PERMISSION_LOADING"